apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-o3x7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-o3x7@sha256:1181c777d4579178cd2d86872a27b39ac356ee376d4d3afc395db98aee221f07
        name: my-nodejs
        resources: {}
status: {}
